### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by twsl** [EnricoMi/publish-unit-test-result-action#167]
Config:
```
  - name: Publish Unit Test Results
    uses: EnricoMi/publish-unit-test-result-action@v1
    with:
      files: artifacts/**/*.xml
```

Following error suddenly occured after a pull request was created by dependabot. Worked correctly once I triggered the workflow run manually:
```
 Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 283, in <module>
    main(settings, gha)
  File "/action/publish_unit_test_results.py", line 96, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line 63, in publish
    check_run = self.publish_check(stats, cases, conclusion)
  File "/action/publish/publisher.py", line 202, in publish_check
    output=output)
  File "/usr/local/lib/python3.6/site-packages/github/Repository.py", line 3645, in create_check_run
    input=post_parameters,
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}
```

**Comment by twsl** [comment]
Dependabot seems to be the culprit: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

**Comment by EnricoMi** [comment]
Just for reference: another reason for this error can be missing permissions:
https://github.com/EnricoMi/publish-unit-test-result-action#permissions
