### ISSUE TITLE
suddenly action fails today

### ISSUE THREAD

**Issue by jurgenvinju** [EnricoMi/publish-unit-test-result-action#250]
Thanks for making this action! It's quite nice to have.

Yesterday, the action started failing with this trace. I'm not sure if it's something on our side that triggered it or not. We do have a lot of failing tests in this project, which are ignored by a flag on the test action. That was never an issue before. 

<https://github.com/usethesource/rascal-core/runs/6112088376?check_suite_focus=true>

```
 2022-04-21 13:29:23 +0000 - publish-unit-test-results -  INFO - reading target/surefire-reports/**/*.xml
  2022-04-21 13:29:24 +0000 - publish -  INFO - publishing failure results for commit a074b5e8be95a4e6367c6af579f31e768fd77845
  2022-04-21 13:29:26 +0000 - publish -  INFO - created check https://github.com/usethesource/rascal-core/runs/6112893594
  Traceback (most recent call last):
    File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/v1/composite/../python/publish_unit_test_results.py", line 331, in <module>
      main(settings, gha)
    File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/v1/composite/../python/publish_unit_test_results.py", line 102, in main
      Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
    File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/v1/python/publish/publisher.py", line 97, in publish
      check_run = self.publish_check(stats, cases, conclusion)
    File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/v1/python/publish/publisher.py", line 289, in publish_check
      check_run.edit(output=output)
    File "/home/runner/.local/lib/python3.8/site-packages/github/CheckRun.py", line 261, in edit
      headers, data = self._requester.requestJsonAndCheck(
    File "/home/runner/.local/lib/python3.8/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
      return self.__check(
    File "/home/runner/.local/lib/python3.8/site-packages/github/Requester.py", line 378, in __check
      raise self.__createException(status, responseHeaders, output)
  github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "CheckRun", "code": "invalid", "field": "annotations"}], "documentation_url": "https://docs.github.com/rest/reference/checks#update-a-check-run"}
  Error: Process completed with exit code 1.
```

**Comment by EnricoMi** [comment]
Can you please add this to the action:

```yaml
with:
  root_log_level: DEBUG
  log_level: DEBUG
```

This will show what content is sent to the Github API that fails validation.

**Comment by jurgenvinju** [comment]
ok. will do!

**Comment by EnricoMi** [comment]
Thanks for adding the debug level. I have extracted the faulty request and am investigating.

**Comment by EnricoMi** [comment]
The problem here is that Github's Checks API does not like unicode characters above 0xffff and the last chunk of annotations contained two annotations that had a few of those characters, e.g. `𒍺𡓿𠄉`.

In #251, the string content taken from the test result files are checked for such characters and replaced, so that the API accepts the payload.

**Comment by EnricoMi** [comment]
This has been fixed and released. Thanks for reporting!

**Comment by DavyLandman** [comment]
Gotta love surrogate pair unicode characters ;)
