### ISSUE TITLE
Forbidden: "resource not accessible by integration"

### ISSUE THREAD

**Issue by ndr-brt** [EnricoMi/publish-unit-test-result-action#284]
Hi, since May 18th we started to get a forbidden error with a `"Resource not accessible by integration"` error message

Here's the console output with DEBUG output (full output: https://github.com/ndr-brt/DataSpaceConnector/runs/6551187190)

```console
2022-05-23 08:00:06 +0000 - publish - DEBUG - there are 0 check runs with title Unit Test Results
2022-05-23 08:00:06 +0000 - publish - DEBUG - stats with delta: UnitTestRunResults(files=79, errors=[], suites=79, duration=439, tests=527, tests_succ=521, tests_skip=6, tests_fail=0, tests_error=0, runs=530, runs_succ=524, runs_skip=6, runs_fail=0, runs_error=0, commit='105169ec3ed89351f88a411f198c0b22439d662d')
2022-05-23 08:00:06 +0000 - publish - DEBUG - creating check with 0 annotations
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - sleeping 0.2427000999[45](https://github.com/ndr-brt/DataSpaceConnector/runs/6551187190?check_suite_focus=true#step:4:46)06836s before next GitHub request
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - GitHub request: POST /repos/ndr-brt/DataSpaceConnector/check-runs
2022-05-23 08:00:06 +0000 - urllib3.connectionpool - DEBUG - [https://api.github.com:443](https://api.github.com/) "POST /repos/ndr-brt/DataSpaceConnector/check-runs HTTP/1.1" 403 None
2022-05-23 08:00:06 +0000 - publish-unit-test-results - WARNING - Request POST /repos/ndr-brt/DataSpaceConnector/check-runs failed: Forbidden
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - Response headers:
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Server: GitHub.com
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Date: Mon, 23 May 2022 08:00:06 GMT
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Content-Type: application/json; charset=utf-8
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Transfer-Encoding: chunked
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - X-GitHub-Media-Type: github.v3; format=json
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - X-RateLimit-Limit: 1000
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - X-RateLimit-Remaining: 991
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - X-RateLimit-Reset: 1653295869
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - X-RateLimit-Used: 9
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - X-RateLimit-Resource: core
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Access-Control-Allow-Origin: *
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - X-Frame-Options: deny
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - X-Content-Type-Options: nosniff
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - X-XSS-Protection: 0
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Content-Security-Policy: default-src 'none'
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Vary: Accept-Encoding, Accept, X-Requested-With
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - Content-Encoding: gzip
2022-05-23 08:00:06 +0000 - publish-unit-test-results - DEBUG - - X-GitHub-Request-Id: 07C0:25D6:4571:FADA:628B3F06
Warning: Request POST /repos/ndr-brt/DataSpaceConnector/check-runs failed with 403: Forbidden
2022-05-23 08:00:06 +0000 - publish - WARNING - Request POST /repos/ndr-brt/DataSpaceConnector/check-runs failed with 403: Forbidden
2022-05-23 08:00:06 +0000 - publish-unit-test-results -  INFO - There is no Retry-After given in the response header
2022-05-23 08:00:06 +0000 - publish-unit-test-results -  INFO - Response message does not indicate retry-able error
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 332, in <module>
    main(settings, gha)
  File "/action/publish_unit_test_results.py", line 102, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line 98, in publish
    check_run, before_check_run = self.publish_check(stats, cases, conclusion)
  File "/action/publish/publisher.py", line 287, in publish_check
    check_run = self._repo.create_check_run(name=self._settings.check_name,
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 3642, in create_check_run
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line [52](https://github.com/ndr-brt/DataSpaceConnector/runs/6551187190?check_suite_focus=true#step:4:53)8, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/action/publish_unit_test_results.py", line 124, in throttled_gh_request_raw
    return gh_request_raw(cnx, verb, url, requestHeaders, input)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line [55](https://github.com/ndr-brt/DataSpaceConnector/runs/6551187190?check_suite_focus=true#step:4:56)5, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line [57](https://github.com/ndr-brt/DataSpaceConnector/runs/6551187190?check_suite_focus=true#step:4:58)7, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line [64](https://github.com/ndr-brt/DataSpaceConnector/runs/6551187190?check_suite_focus=true#step:4:65)5, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 8[66](https://github.com/ndr-brt/DataSpaceConnector/runs/6551187190?check_suite_focus=true#step:4:67), in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/action/publish/retry.py", line [101](https://github.com/ndr-brt/DataSpaceConnector/runs/6551187190?check_suite_focus=true#step:4:102), in increment
    raise GithubException(response.status, content, response.headers)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}
```

**Comment by EnricoMi** [comment]
You have restricted permissions in that workflow on May 18th:
https://github.com/ndr-brt/DataSpaceConnector/commit/3e4b95654f3fd3d88d2c7f3a2463069271508a5e#diff-1440bd8668b126838d91c4736aa5d2dfe6429e97a2e0a45b1a0ac5562ab990ff

This action requires a few permissions: https://github.com/EnricoMi/publish-unit-test-result-action#permissions

Add those permissions to the publish job `"Upload-Test-Report" (not the entire workflow).

**Comment by ndr-brt** [comment]
@EnricoMi that was easy, thank you for your support

**Comment by EnricoMi** [comment]
I am glad it wasn't my latest release that happened on the same day.
