### ISSUE TITLE
Getting 403 Forbidden while using ubuntu runner

### ISSUE THREAD

**Issue by lokesh-arora-oaknorth** [EnricoMi/publish-unit-test-result-action#301]
The reports are created in a target/surefire-reports folder at runtime.
I'm using v1.36 to publish the reports but getting 403 forbidden when I run the build.

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.36
      if: always()
      with:
        files: "./auth-service/target/surefire-reports/*.xml"
        
I have tried to run ls -lrth on the same path and I can see reports exist but I get this WARNING : 403 Forbidden and workflow fails.

2022-06-06 14:12:51 +0000 - publish-unit-test-results -  INFO - reading ./auth-service/target/surefire-reports/*.xml
2022-06-06 14:12:53 +0000 - publish -  INFO - publishing success results for commit f80c69a4ef92[30](https://github.com/org_name/reponame/runs/6756831054?check_suite_focus=true#step:9:31)f1414add8ffc3162b908
2022-06-06 14:12:53 +0000 - publish-unit-test-results - WARNING - Request GET /repos/org_name/reponame/commits/8ab1c2b99fc08cea03e0e5b097698c87da/check-runs?per_page=100 failed: Forbidden
Warning: Request GET /repos/org_name/reponame/commits/8ab1c2b99fc08cea03e0e5b097698c87da/check-runs?per_page=100 failed with 403: Forbidden
2022-06-06 14:12:51 +0000 - publish-unit-test-results -  INFO - reading ./auth-service/target/surefire-reports/*.xml
2022-06-06 14:12:53 +0000 - publish -  INFO - publishing success results for commit f80c69a4ef92[30](https://github.com/org_name/reponame/runs/6756831054?check_suite_focus=true#step:9:31)f1414add8ffc3162b908
2022-06-06 14:12:53 +0000 - publish-unit-test-results - WARNING - Request GET /repos/org_name/reponame/commits/8ab1c2b99fc08cea03e0e5b097698c87da/check-runs?per_page=100 failed: Forbidden
Warning: Request GET /repos/org_name/reponame/commits/8ab1c2b99fc08cea03e0e5b097698c87da/check-runs?per_page=100 failed with 403: Forbidden

**Comment by lokesh-arora-oaknorth** [comment]
Hey Enrico, I managed to get past this error by adding the write permissions. But after that I'm getting stuck with this error!

2022-06-06 15:02:56 +0000 - publish-unit-test-results -  INFO - reading ./auth-service/target/surefire-reports/*.xml
2022-06-06 15:02:56 +0000 - publish -  INFO - publishing success results for commit 93e7371e7dff3579516dec5699557a11ed4ed14d
2022-06-06 15:02:58 +0000 - publish -  INFO - created check https://github.com/org_name/reponame/runs/6757700520
2022-06-06 15:02:58 +0000 - publish -  INFO - created job summary
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line [33](https://github.com/org_name/reponame/runs/6757681779?check_suite_focus=true#step:9:34)3, in <module>
    main(settings, gha)
  File "/action/publish_unit_test_results.py", line 102, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line 145, in publish
    pulls = self.get_pulls(self._settings.commit)
  File "/action/publish/publisher.py", line 163, in get_pulls
    issues = list(self._gh.search_issues(f'type:pr repo:"{self._settings.repo}" {commit}'))
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line [35](https://github.com/org_name/reponame/runs/6757681779?check_suite_focus=true#step:9:36)3, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line [37](https://github.com/org_name/reponame/runs/6757681779?check_suite_focus=true#step:9:38)8, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: [42](https://github.com/org_name/reponame/runs/6757681779?check_suite_focus=true#step:9:43)2 {"message": "Validation Failed", "errors": [{"message": "The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource": "Search", "field": "q", "code": "invalid"}], "documentation_url": "https://docs.github.com/v3/search/"}


As a result of this error, my step "Build and Publish" fails although the step "Unit Test Results" is showing success.
I tried to check publish_unit_test_results.py in your code, but I have limited understanding of Python so wasn't able to determine if issue lies within the action or am I still missing something w.r.t permissions or access.

**Comment by EnricoMi** [comment]
Have you set **all** permissions noted here: https://github.com/EnricoMi/publish-unit-test-result-action#permissions?

**Comment by lokesh-arora-oaknorth** [comment]
Thanks for your help. After including the required permissions, it's working as expected.
Thanks again :)
