### ISSUE TITLE
Obtuse Error in Test Reporting

### ISSUE THREAD

**Issue by kalverra** [EnricoMi/publish-unit-test-result-action#314]
[Affected Workflow Run](https://github.com/smartcontractkit/chainlink/runs/7137131084?check_suite_focus=true)

We've run into an odd bug when trying to report a passing test. Judging by the error trace, it's failing when trying to compare to previous runs? See the [full PR](https://github.com/smartcontractkit/chainlink/pull/6898).

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1697, in isEnabledFor
    return self._cache[level]
KeyError: 10
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 386, in <module>
    settings = get_settings(options, gha)
  File "/action/publish_unit_test_results.py", line 331, in get_settings
    commit=get_var('COMMIT', options) or get_commit_sha(event, event_name, options),
  File "/action/publish_unit_test_results.py", line 165, in get_commit_sha
    logger.debug(f"action triggered by '{event_name}' event")
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1433, in debug
    if self.isEnabledFor(DEBUG):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1705, in isEnabledFor
    level >= self.getEffectiveLevel()
TypeError: '>=' not supported between instances of 'int' and 'str'
```

Using these settings 

```yaml
  with:
    files: ./tests-smoke-report.xml
    github_token: ***
    check_name: EVM Smoke Test Results
    comment_mode: always
    github_retries: 10
    fail_on: test failures
    time_unit: seconds
    ignore_runs: false
    hide_comments: all but latest
    job_summary: true
    compare_to_earlier_commit: true
    pull_request_build: merge
    check_run_annotations: all tests, skipped tests
    seconds_between_github_reads: 0.25
    seconds_between_github_writes: 2.0
    json_thousands_separator:  
  env:
    AWS_DEFAULT_REGION: ***
    AWS_REGION: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    KUBECONFIG: /home/runner/work/_temp/kubeconfig_1656612353469
    CHAINLINK_COMMIT_SHA: 8846d5c50eaf1cbb0b1580a144112c40fb125dd1
    CHAINLINK_ENV_USER: kalverra
    TEST_TRIGGERED_BY: core-CI
    LOG_LEVEL: debug
```

**Comment by EnricoMi** [comment]
Yes, log levels are case sensitive, it should be `DEBUG`. I have fixed the case-sensitivity and improved the error message. Should be fixed in next release.
