### ISSUE TITLE
github.GithubException.RateLimitExceededException (403)

### ISSUE THREAD

**Issue by jamesbrink** [EnricoMi/publish-unit-test-result-action#384]
I have only seen this on one job run recently, but from my understanding based on the options in this action this should retry up to 10 times by default. I have not had the time to dig into the action, but I have a provided the stack trace that occurred. For context the job ran for 3s, so it does not look like it reached the retry functionality. 

I am using the latest V2

```yaml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "**/test-results/**/*.xml"
```

Stack trace
```
2022-12-08 00:43:17 +0000 - publish -  INFO - creating check
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 225, in <module>
    main(settings, gha)
  File "/action/publish_unit_test_results.py", line 87, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line 63, in publish
    pull = self.get_pull(self._settings.commit)
  File "/action/publish/publisher.py", line 79, in get_pull
    logger.debug(f'found {issues.totalCount} pull requests in repo {self._settings.repo} for commit {commit}')
  File "/usr/local/lib/python3.6/site-packages/github/PaginatedList.py", line 150, in totalCount
    "GET", self.__firstUrl, parameters=params, headers=self.__headers
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line [31](https://github.com/the-nft-company/nftco-platform/actions/runs/3644043891/jobs/6152875796#step:18:32)7, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line [34](https://github.com/the-nft-company/nftco-platform/actions/runs/3644043891/jobs/6152875796#step:18:35)0, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: [40](https://github.com/the-nft-company/nftco-platform/actions/runs/3644043891/jobs/6152875796#step:18:41)3 {"documentation_url": "https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits", "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again."}
```

**Comment by EnricoMi** [comment]
From the log it appears that this is not v2 but v1.18. Can you please provide me with the full log of the action?

In the job that contains the publish action, there should be a step like "Pull ghcr.io/enricomi/publish-unit-test-result-action:v2.2.0". Can you provide the log for that step please as well?

**Comment by jamesbrink** [comment]
Ah, you're right! this was the old version. My apologies! I think it was a stale branch being run so there is no issue. I have no idea how i missed this
