### ISSUE TITLE
junitparser.junitparser.JUnitXmlError: Invalid format. - Maven Failsafe Plugin Reports

### ISSUE THREAD

**Issue by khmarbaise** [EnricoMi/publish-unit-test-result-action#389]
Currently using the action to report the test result which unfortunately produce an error while parsing the maven-failsafe-plugin report (with a `Invalid format` error).

```
Publish Test Results
  2022-12-29 12:28:58 +0000 - publish -  INFO - Available memory to read files: 6.0 GiB
  2022-12-29 12:28:58 +0000 - publish -  INFO - Reading JUnit files /home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/*.xml
  /home/runner/work/maven-it-extension/maven-it-extension/itf-failure-plugin/target/failsafe-reports/*.xml
  /home/runner/work/maven-it-extension/maven-it-extension/itf-maven-plugin/target/failsafe-reports/*.xml
   (56 files, 413.3 KiB)
  2022-12-29 12:28:58 +0000 - publish -  INFO - Finished reading 56 files in 0.03 seconds
  2022-12-29 12:28:58 +0000 - publish - ERROR - junitparser.junitparser.JUnitXmlError: Invalid format.
  2022-12-29 12:28:58 +0000 - publish - ERROR - junitparser.junitparser.JUnitXmlError: Invalid format.
  2022-12-29 12:28:58 +0000 - publish - ERROR - junitparser.junitparser.JUnitXmlError: Invalid format.
  2022-12-29 12:28:59 +0000 - publish -  INFO - Publishing failure results for commit e37b51ca4aec302fd1decd65fdc95c7ba563d720
  2022-12-29 12:29:01 +0000 - publish -  INFO - Created check https://github.com/khmarbaise/maven-it-extension/runs/10349527100
  2022-12-29 12:29:01 +0000 - publish -  INFO - Created job summary
  2022-12-29 12:29:06 +0000 - publish -  INFO - Edited comment for pull request #299: https://github.com/khmarbaise/maven-it-extension/pull/299#issuecomment-[131](https://github.com/khmarbaise/maven-it-extension/actions/runs/3800447931/jobs/6463936590#step:8:137)6008874
  Error: junitparser.junitparser.JUnitXmlError: Invalid format.
  Error: Error processing result file: Invalid format.
  Error: junitparser.junitparser.JUnitXmlError: Invalid format.
  Error: Error processing result file: Invalid format.
  Error: junitparser.junitparser.JUnitXmlError: Invalid format.
  Error: Error processing result file: Invalid format.
```

Also turned on debugging and got:
```
'/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.mps.MavenProjectSourcesLocationThreeIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-maven-plugin/target/failsafe-reports/failsafe-summary.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.EARIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.subdir.SubDirIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.repository.MavenRepositoryNestedIT$NestedIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.subdir.SubDirNestedMultipleIT$DirNested$Level1.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.MavenProjectIT$NestedExample.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.properties.PropertiesOnNestedClassIT$Level1.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.options.OptionsOnClassIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.mps.MavenProjectSourcesMoreComplexIT$Level1.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.options.OptionsIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.MavenProjectRootIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.MavenIntegrationExampleNestedWithoutNoneNestedTestGlobalRepoIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.MavenIntegrationExampleNestedWithoutNoneNestedTestGlobalRepoIT$NestedExample.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.subdir.SubDirClassIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.profiles.ProfileOnClassIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.subdir.SubDirNestedIT$DirNested.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.profiles.ProfileIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-maven-plugin/target/failsafe-reports/TEST-com.soebes.itf.maven.plugin.BasicIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-failure-plugin/target/failsafe-reports/TEST-com.soebes.itf.maven.plugin.failure.FailureIT.xml', '/home/runner/work/maven-it-extension/maven-it-extension/itf-examples/target/failsafe-reports/TEST-com.soebes.itf.examples.properties.PropertiesOnClassIT.xml']
2022-12-29T12:54:57.1394827Z 2022-12-29 12:54:57 +0000 - publish -  INFO - Finished reading 56 files in 0.02 seconds
2022-12-29T12:54:57.1436880Z 2022-12-29 12:54:57 +0000 - publish - ERROR - junitparser.junitparser.JUnitXmlError: Invalid format.
2022-12-29T12:54:57.1437493Z 2022-12-29 12:54:57 +0000 - publish - DEBUG - Traceback (most recent call last):
2022-12-29T12:54:57.1438260Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -   File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/v2/python/publish/junit.py", line 161, in create_junitxml
2022-12-29T12:54:57.1438944Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -     instance = JUnitXml.fromroot(tree.getroot())
2022-12-29T12:54:57.1440097Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -   File "/home/runner/.local/lib/python3.10/site-packages/junitparser/junitparser.py", line 311, in fromroot
2022-12-29T12:54:57.1440710Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -     raise JUnitXmlError("Invalid format.")
2022-12-29T12:54:57.1441314Z 2022-12-29 12:54:57 +0000 - publish - DEBUG - junitparser.junitparser.JUnitXmlError: Invalid format.
2022-12-29T12:54:57.1442198Z 2022-12-29 12:54:57 +0000 - publish - ERROR - junitparser.junitparser.JUnitXmlError: Invalid format.
2022-12-29T12:54:57.1442742Z 2022-12-29 12:54:57 +0000 - publish - DEBUG - Traceback (most recent call last):
2022-12-29T12:54:57.1443493Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -   File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/v2/python/publish/junit.py", line 161, in create_junitxml
2022-12-29T12:54:57.1444178Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -     instance = JUnitXml.fromroot(tree.getroot())
2022-12-29T12:54:57.1444952Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -   File "/home/runner/.local/lib/python3.10/site-packages/junitparser/junitparser.py", line 311, in fromroot
2022-12-29T12:54:57.1445564Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -     raise JUnitXmlError("Invalid format.")
2022-12-29T12:54:57.1446151Z 2022-12-29 12:54:57 +0000 - publish - DEBUG - junitparser.junitparser.JUnitXmlError: Invalid format.
2022-12-29T12:54:57.1447203Z 2022-12-29 12:54:57 +0000 - publish - ERROR - junitparser.junitparser.JUnitXmlError: Invalid format.
2022-12-29T12:54:57.1447747Z 2022-12-29 12:54:57 +0000 - publish - DEBUG - Traceback (most recent call last):
2022-12-29T12:54:57.1448545Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -   File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/v2/python/publish/junit.py", line 161, in create_junitxml
2022-12-29T12:54:57.1449224Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -     instance = JUnitXml.fromroot(tree.getroot())
2022-12-29T12:54:57.1449911Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -   File "/home/runner/.local/lib/python3.10/site-packages/junitparser/junitparser.py", line 311, in fromroot
2022-12-29T12:54:57.1450525Z 2022-12-29 12:54:57 +0000 - publish - DEBUG -     raise JUnitXmlError("Invalid format.")
2022-12-29T12:54:57.1451097Z 2022-12-29 12:54:57 +0000 - publish - DEBUG - junitparser.junitparser.JUnitXmlError: Invalid format.
2022-12-29T12:54:57.1451709Z 2022-12-29 12:54:57 +0000 - publish - DEBUG - GitHub request: GET /repos/khmarbaise/maven-it-extension
2022-12-29T12:54:57.1470612Z 2022-12-29 12:54:57 +0000 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.github.com:443
2022-12-29T12:54:57.4029410Z 2022-12-29 12:54:57 +0000 - urllib3.connectionpool - DEBUG - https://api.github.com:443 "GET /repos/khmarbaise/maven-it-extension HTTP/1.1" 200 None
2022-12-29T12:54:57.4060095Z 2022-12-29 12:54:57 +0000 - github.Requester - DEBUG - GET https://api.github.com/repos/khmarbaise/maven-it-extension {'Authorization': 'token (oauth token removed)', 'User-Agent': 'PyGithub/Python'} None ==> 200 {'server': 'GitHub.com', 'date': 'Thu, 29 Dec 2022 12:54:57 GMT', 'content-type': 'application/json; charset=utf-8', 'transfer-encoding': 'chunked', 'cache-control': 'private, max-age=60, s-maxage=60', 'vary': 'Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With', 'etag': 'W/"3142712b69bae9ae4c133efd96e9d307b1480ac0aa70458f384dd2194f3065b9"', 'last-modified': 'Fri, 09 Dec 2022 19:57:26 GMT', 'x-github-media-type': 'github.v3; format=json', 'x-github-api-version-selected': '2022-11-28', 'x-ratelimit-limit': '1000', 'x-ratelimit-remaining': '923', 'x-ratelimit-reset': '1672320475', 'x-ratelimit-used': '77', 'x-ratelimit-resource': 'core', 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAut
```

An full example how it looks like can be found here:

https://github.com/khmarbaise/maven-it-extension/actions/runs/3800599816/jobs/6464233284

**Comment by EnricoMi** [comment]
Thanks for reporting, I am looking into this. And thanks for supporting!

**Comment by EnricoMi** [comment]
The failing files (`failsafe-summary.xml`) are not JUnit XML files but Failsafe Summary XML files (`https://maven.apache.org/surefire/maven-surefire-plugin/xsd/failsafe-summary.xsd`):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<failsafe-summary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/failsafe-summary.xsd" result="null" timeout="false">
    <completed>3</completed>
    <errors>0</errors>
    <failures>0</failures>
    <skipped>0</skipped>
    <failureMessage xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
</failsafe-summary>
```

Exclude those from your file patterns, either by ristricting to `TEST-*.xml` or excluding `failsafe-summary.xml`:
```yaml
        with:
          junit_files: |
            ${{ github.workspace }}/itf-examples/target/failsafe-reports/TEST-*.xml
            ${{ github.workspace }}/itf-failure-plugin/target/failsafe-reports/TEST-*.xml
            ${{ github.workspace }}/itf-maven-plugin/target/failsafe-reports/TEST-*.xml
```
or
```yaml
        with:
          junit_files: |
            ${{ github.workspace }}/itf-examples/target/failsafe-reports/*.xml
            ${{ github.workspace }}/itf-failure-plugin/target/failsafe-reports/*.xml
            ${{ github.workspace }}/itf-maven-plugin/target/failsafe-reports/*.xml
            !${{ github.workspace }}/*/target/failsafe-reports/failsafe-summary.xml
```

**Comment by EnricoMi** [comment]
In the directories with the `failsafe-summary.xml` file, there are `TEST-*.xml` files that contain test results:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-failsafe-plugin/xsd/failsafe-test-report-3.0.xsd" version="3.0" name="com.soebes.itf.maven.plugin.failure.FailureIT" time="11.279" tests="3" errors="0" skipped="0" failures="0">
  <testcase name="basic_configuration(MavenExecutionResult)" classname="com.soebes.itf.maven.plugin.failure.FailureIT" time="6.147"/>
  <testcase name="fail_with_mojo_failure_exception(MavenExecutionResult)" classname="com.soebes.itf.maven.plugin.failure.FailureIT" time="2.556"/>
  <testcase name="fail_with_mojo_execution_exception(MavenExecutionResult)" classname="com.soebes.itf.maven.plugin.failure.FailureIT" time="2.543"/>
</testsuite>
```

**Comment by khmarbaise** [comment]
Outch... Thanks I will check that. Thank you for finding **my** issue. The problem is sitting in front of the keyboard. So it's not an issue. It's a wrong configuration.
