### ISSUE TITLE
CData section too big found

### ISSUE THREAD

**Issue by kamilwozniak4213** [EnricoMi/publish-unit-test-result-action#399]
### Problem description
We are currently experiencing problems with the publishing of XML results. 
We are running into `CData section too big found` errors like shown in the log extract below.

### Log

```sh
2023-01-24 14:35:04 +0000 - publish - ERROR - lxml.etree.XMLSyntaxError: CData section too big found, line 2531, column 394
2023-01-24 14:35:04 +0000 - publish - DEBUG - Traceback (most recent call last):
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "/action/publish/junit.py", line 133, in safe_parse_xml_file
2023-01-24 14:35:04 +0000 - publish - DEBUG -     return parse(path)
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "/action/publish/junit.py", line 153, in parse
2023-01-24 14:35:04 +0000 - publish - DEBUG -     return etree.parse(path)
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "src/lxml/etree.pyx", line 3538, in lxml.etree.parse
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 1902, in lxml.etree._parseDocumentFromURL
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
2023-01-24 14:35:04 +0000 - publish - DEBUG -   File "./build/test-results/test/TEST-test.xml", line 2531
```

All help is appreciated. 

Greeting
Kamil

**Comment by EnricoMi** [comment]
Would you say your files are in general very large, or would you expect the file should be OK to be parsed?

To get more context, would you mind providing log lines like these as well?

```
2023-01-24 16:35:11 +0000 - publish -  INFO - Available memory to read files: 5.9 GiB
2023-01-24 16:35:11 +0000 - publish -  INFO - Reading JUnit files artifacts/**/*.xml (69 files, 2.8 MiB)
```

**Comment by EnricoMi** [comment]
Looks like the XML parser has a limit of 10MB for CData. You could run the action with `ignore_runs: true`, which will not load individual test cases and increase the CData limit to 1GB. The report will then not include individual runs or test failure details.

**Comment by kamilwozniak4213** [comment]
Hi, it looks like we have a lot of files and they are also large.

```
2023-01-24 14:35:03 +0000 - publish -  INFO - Available memory to read files: 5.5 GiB
2023-01-24 14:35:03 +0000 - publish -  INFO - Reading JUnit files ./**/build/test-results/test/TEST-*.xml (237 files, 595.1 MiB)
```

You suggested `The report will then not include individual runs or test failure details.` Does this mean that we would loose the stacktraces from all the failing tests?

**Comment by EnricoMi** [comment]
Yes, that would happen and would not be very useful. Ignore that suggestion, try the following:

    uses: EnricoMi/publish-unit-test-result-action/composite@branch-parse-xml-huge-tree

That will parse the XML with 1GB limit for CData elements. Lets see if 5.5GB RAM is sufficient to load the XML files.

**Comment by kamilwozniak4213** [comment]
@EnricoMi Thanks, we will check this out!

**Comment by thko79** [comment]
Hi @EnricoMi,

I'm a colleague of @kamilwozniak4213. We've tried your fixed version 

**EnricoMi/publish-unit-test-result-action/composite@branch-parse-xml-huge-tree**, 

but we still got parsing errors for big CDATA sections:   

Log
```
2023-01-31 14:19:08 +0000 - publish -  INFO - Finished reading 239 files in 0.95 seconds
2023-01-31 14:19:08 +0000 - publish - ERROR - lxml.etree.XMLSyntaxError: CData section too big found, line 2627, column 3946
2023-01-31 14:19:08 +0000 - publish - DEBUG - Traceback (most recent call last):
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/branch-parse-xml-huge-tree/python/publish/junit.py", line 133, in safe_parse_xml_file
2023-01-31 14:19:08 +0000 - publish - DEBUG -     return parse(path)
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/branch-parse-xml-huge-tree/python/publish/junit.py", line 158, in parse
2023-01-31 14:19:08 +0000 - publish - DEBUG -     return etree.parse(path)
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "src/lxml/etree.pyx", line 3538, in lxml.etree.parse
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 1902, in lxml.etree._parseDocumentFromURL
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
2023-01-31 14:19:08 +0000 - publish - DEBUG -   File "./build/test-results/test/TEST-test.xml", line 2627
2023-01-31 14:19:08 +0000 - publish - DEBUG - lxml.etree.XMLSyntaxError: CData section too big found, line 2627, column 3946
```

Do you have any idea?

Greeting
Thomas

**Comment by EnricoMi** [comment]
Sorry, you have to run the action in that branch with `large_files: true`.

**Comment by thko79** [comment]
@EnricoMi Thanks, we'll try it today again and give you feedback soon

**Comment by EnricoMi** [comment]
@thko79 did you manage to test this?

**Comment by thko79** [comment]
Hi @EnricoMi, yes I think it's doing well now. Sorry for the late feedback, we had to wait for an update causing some more errors and creating these huge files. For now we are happy with this solution, so you can close this issue.

Thank you very much!
