### ISSUE TITLE
403: Forbidden when issues are disabled in repository

### ISSUE THREAD

**Issue by oscar-b** [EnricoMi/publish-unit-test-result-action#403]
For a private repository which has Issues disabled, it results in `403: Forbidden` even with `issues: read` permission.

**Comment by EnricoMi** [comment]
That is interesting, so when pull requests are disabled on a repo, the pull request API always response with this error.

I think the best you can do is to disable commenting on pull requests:

```yaml
with:
  comment_mode: off
```

**Comment by oscar-b** [comment]
Well we have issues disabled, but not pull requests. And PR comments work just fine, it seems like the action tries to find something in issues? Haven’t looked into the code any closer yet..

**Comment by EnricoMi** [comment]
For github, pull requests are issues, so they sit behind the same API. I'll investigate how to make this work with issues disabled but pull requests enabled.

**Comment by EnricoMi** [comment]
You probably saw something like this (I just saw that in one of my logs):

```
2023-02-17 07:11:11 +0000 - publish - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22horovod%2Fhorovod%22+d4c7b3f5f88a7a5bc09d3752be8f6a5bdff8d006&per_page=100 failed with 403: Forbidden
2023-02-17 07:11:11 +0000 - publish -  INFO - There is no Retry-After given in the response header
2023-02-17 07:11:11 +0000 - publish -  INFO - Response body indicates retry-able error: you have exceeded a secondary rate limit. please wait a few minutes before you try again.
2023-02-17 07:11:11 +0000 - publish -  INFO - Reset occurs in 0:00:59.660187 (1676617931 / 2023-02-17 07:12:11), setting next backoff to 59.660187s
```

This is the secondary rate limit error.

**Comment by blabno** [comment]
So what is the solution?

**Comment by EnricoMi** [comment]
> So what is the solution?

The solution to what, the secondary rate limit error?

**Comment by blabno** [comment]
Yes, it's crashing my run.

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/action/publish_test_results.py", line 525, in <module>
    main(settings, gha)
  File "/action/publish_test_results.py", line 246, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line 199, in publish
    pulls = self.get_pulls(self._settings.commit)
  File "/action/publish/publisher.py", line 211, in get_pulls
    issues = list(self._gh.search_issues(f'type:pr repo:"{self._settings.repo}" {commit}'))
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 201, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/action/publish_test_results.py", line 274, in throttled_gh_request_raw
    return gh_request_raw(cnx, verb, url, requestHeaders, input)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line [127](https://github.com/blabno/xxx/actions/runs/4435161365/jobs/7781971046#step:19:128), in getresponse
    r = verb(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/issues?q=type%3Apr+repo%3A%22blabno%2Fxxx%22+dc4d97f7a9e07ca03e2c7ce7b7e9efee45305583&per_page=100 (Caused by ResponseError('too many 403 error responses'))

**Comment by EnricoMi** [comment]
@oscar-b @blabno  please note that this issue should have been resolved with the latest release 2.6.0 (yesterday). Please check if you have seen Forbidden errors with the latest versions.

**Comment by blabno** [comment]
> @oscar-b @blabno please note that this issue should have been resolved with the latest release 2.6.0 (yesterday). Please check if you have seen Forbidden errors with the latest versions.

Logs clean now. Thank you.
