### ISSUE TITLE
Secondary Rate limit errors

### ISSUE THREAD

**Issue by cmergenthaler** [EnricoMi/publish-unit-test-result-action#419]
Hey,

we are running into secondary rate limits from time to time:

private repo within github enterprise cloud orga.

```log
2023-03-09 09:04:42 +0000 - publish -  INFO - Created check https://github.com/repo/runs/11874889807
2023-03-09 09:04:42 +0000 - publish - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22reüp%22+332fbe0d3211de7a9f9376f40494878b132a84fd&per_page=100 failed: Forbidden
2023-03-09 09:04:42 +0000 - publish - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22repo%22+332fbe0d3211de7a9f9376f40494878b132a84fd&per_page=100 failed with 403: Forbidden
2023-03-09 09:04:42 +0000 - publish -  INFO - There is no Retry-After given in the response header
2023-03-09 09:04:42 +0000 - publish -  INFO - Response body indicates retry-able error: you have exceeded a secondary rate limit. please wait a few minutes before you try again.
2023-03-09 09:04:42 +0000 - publish -  INFO - Reset occurs in 0:00:59.473329 (1678352742 / 2023-03-09 09:05:42), setting next backoff to 59.473329s
2023-03-09 09:05:43 +0000 - publish - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22repo%22+332fbe0d3211de7a9f9376f40494878b132a84fd&per_page=100 failed: Forbidden
2023-03-09 09:05:43 +0000 - publish - WARNING - Request GET /search/issues?q=type%3Apr+repo%3A%22repo%22+332fbe0d3211de7a9f9376f40494878b132a84fd&per_page=100 failed with 403: Forbidden
2023-03-09 09:05:43 +0000 - publish -  INFO - There is no Retry-After given in the response header
2023-03-09 09:05:43 +0000 - publish -  INFO - Response body indicates retry-able error: you have exceeded a secondary rate limit. please wait a few minutes before you try again.
2023-03-09 09:05:43 +0000 - publish -  INFO - Reset occurs in 0:00:59.748716 (1678352803 / 2023-03-09 09:06:43), setting next backoff to 59.748716s
```

Here is also the exception:
```log
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/action/publish/retry.py", line 78, in increment
    retry = super().increment(method, url, response, error, _pool, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/issues?q=type%3Apr+repo%3A%22repo%22+332fbe0d3211de7a9f9376f40494878b132a84fd&per_page=100 (Caused by ResponseError('too many 403 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/action/publish_test_results.py", line 524, in <module>
    main(settings, gha)
  File "/action/publish_test_results.py", line 245, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line 199, in publish
    pulls = self.get_pulls(self._settings.commit)
  File "/action/publish/publisher.py", line 211, in get_pulls
    issues = list(self._gh.search_issues(f'type:pr repo:"{self._settings.repo}" {commit}'))
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 201, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/action/publish_test_results.py", line 273, in throttled_gh_request_raw
    return gh_request_raw(cnx, verb, url, requestHeaders, input)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/issues?q=type%3Apr+repo%3A%22repo%22+332fbe0d3211de7a9f9376f40494878b132a84fd&per_page=100 (Caused by ResponseError('too many 403 error responses'))
```

Hope this helps. Tell me if you need more information!

**Comment by EnricoMi** [comment]
Look like this action is doing everything right. GitHub does not like to answer the API calls and the action defers retrying the call. You could increase `github_retries`, but this does not make the secondary rate limit errors go away, the action just keeps retrying more.

Please check with GitHub support to understand why those calls to `/search/issues` hit the secondary rate limit and what can be done about it other than calling that API endpoint less frequently.

**Comment by cmergenthaler** [comment]
As far as I understand the [GH docs](https://docs.github.com/en/enterprise-cloud@latest/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#secondary-rate-limits), the error responses should contain a `retry-after` or, if not present, a `x-ratelimit-reset` header to specifiy the retry time. 
Is the action checking for both headers?

**Comment by EnricoMi** [comment]
The log says:
```
2023-03-09 09:04:42 +0000 - publish -  INFO - There is no Retry-After given in the response header
2023-03-09 09:04:42 +0000 - publish -  INFO - Response body indicates retry-able error: you have exceeded a secondary rate limit. please wait a few minutes before you try again.
2023-03-09 09:04:42 +0000 - publish -  INFO - Reset occurs in 0:00:59.473329 (1678352742 / 2023-03-09 09:05:42), setting next backoff to 59.473329s
```
So yes.

**Comment by EnricoMi** [comment]
@cmergenthaler please note that this issue should have been resolved with the latest release 2.6.0 (yesterday). Please check if you have seen Forbidden errors with the latest versions.

**Comment by cmergenthaler** [comment]
@EnricoMi Thanks! I have updated my workflows and so far everything works well. As this error only occurred from time to time, I will keep observing my runs in the next days.

**Comment by EnricoMi** [comment]
Thanks, please reopen when this resurfaces.
