### ISSUE TITLE
Publishing the Unit test results fails randomly

### ISSUE THREAD

**Issue by saivamsibodavulaTR** [EnricoMi/publish-unit-test-result-action#447]
Hello.,
This is a scenario, we have observed., where the task Publishing Unit test results fails random on random basis., and re running them will success the job.
we have multiple microservices. and during the unit test cases job flow., some of the services fails randomly without any pattern and rerunning them would result in success run.

its failing with the error:  Request GET /search/issues?q=type%3Apr+repo%3A%22tr%2Fhighq_collaborate%22+6b180f9b738992922e67a8e90ed0fcc03b0df216&per_page=100 failed: Forbidden especially while its trying to create a comment in the github actions (either it could be a PR or a push event).

errors observed are: 
------------------------------------------------------------
Warning: Request GET /search/issues?q=type%3Apr+repo%3A%22tr%2Fhighq_collaborate%22+6b180f9b738992922e67a8e90ed0fcc03b0df216&per_page=100 failed with 403: Forbidden
Warning: Request GET /search/issues?q=type%3Apr+repo%3A%22tr%2Fhighq_collaborate%22+6b180f9b738992922e67a8e90ed0fcc03b0df216&per_page=100 failed with 403: Forbidden
Warning: Request GET /search/issues?q=type%3Apr+repo%3A%22tr%2Fhighq_collaborate%22+6b180f9b738992922e67a8e90ed0fcc03b0df216&per_page=100 failed with 403: Forbidden
Warning: Request GET /search/issues?q=type%3Apr+repo%3A%22tr%2Fhighq_collaborate%22+6b180f9b738992922e67a8e90ed0fcc03b0df216&per_page=100 failed with 403: Forbidden
Warning: Request GET /search/issues?q=type%3Apr+repo%3A%22tr%2Fhighq_collaborate%22+6b180f9b738992922e67a8e90ed0fcc03b0df216&per_page=100 failed with 403: Forbidden

---------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 876, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 876, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 876, in urlopen
    return self.urlopen(
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 866, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/action/publish/retry.py", line 78, in increment
    retry = super().increment(method, url, response, error, _pool, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/issues?q=type%3Apr+repo%3A%22tr%2Fhighq_collaborate%22+6b180f9b738992922e67a8e90ed0fcc03b0df216&per_page=100 (Caused by ResponseError('too many 403 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/action/publish_test_results.py", line 387, in <module>
    main(settings, gha)
  File "/action/publish_test_results.py", line 135, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line [150](https://github.com/tr/highq_collaborate/actions/runs/4988318327/jobs/8931533853#step:8:151), in publish
    pulls = self.get_pulls(self._settings.commit)
  File "/action/publish/publisher.py", line 168, in get_pulls
    issues = list(self._gh.search_issues(f'type:pr repo:"{self._settings.repo}" {commit}'))
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/action/publish_test_results.py", line [157](https://github.com/tr/highq_collaborate/actions/runs/4988318327/jobs/8931533853#step:8:158), in throttled_gh_request_raw
    return gh_request_raw(cnx, verb, url, requestHeaders, input)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.github.com', port=443): **Max retries exceeded with url: /search/issues?q=type%3Apr+repo%3A%22tr%2Fhighq_collaborate%22+6b[180]**(https://github.com/tr/highq_collaborate/actions/runs/4988318327/jobs/8931533853#step:8:181)f9b738992922e67a8e90ed0fcc03b0df216&per_page=100Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 876, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 876, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 876, in urlopen
    return self.urlopen(
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 866, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/action/publish/retry.py", line 78, in increment
    retry = super().increment(method, url, response, error, _pool, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /search/issues?q=type%3Apr+repo%3A%22tr%2Fhighq_collaborate%22+6b180f9b738992922e67a8e90ed0fcc03b0df216&per_page=100 (Caused by ResponseError('too many 403 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/action/publish_test_results.py", line 387, in <module>
    main(settings, gha)
  File "/action/publish_test_results.py", line 135, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line [150](https://github.com/tr/highq_collaborate/actions/runs/4988318327/jobs/8931533853#step:8:151), in publish
    pulls = self.get_pulls(self._settings.commit)
  File "/action/publish/publisher.py", line 168, in get_pulls
    issues = list(self._gh.search_issues(f'type:pr repo:"{self._settings.repo}" {commit}'))
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.8/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/action/publish_test_results.py", line [157](https://github.com/tr/highq_collaborate/actions/runs/4988318327/jobs/8931533853#step:8:158), in throttled_gh_request_raw
    return gh_request_raw(cnx, verb, url, requestHeaders, input)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.github.com', port=443): **Max retries exceeded with url: /search/issues?q=type%3Apr+repo%3A%22tr%2Fhighq_collaborate%22+6b[180](https://github.com/tr/highq_collaborate/actions/runs/4988318327/jobs/8931533853#step:8:181)f9b738992922e67a8e90ed0fcc03b0df216&per_page=100 (Caused by ResponseError('too many 403 error responses'))**
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Publish Unit Test Results
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Publish Unit Test Results
--------------------------------------------------------------------------------
Yaml script for this job is given as below: (note: all the env variables are been passed correctly)
 - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/test-results/jUnitTest/*.xml'
          check_name: "${{ matrix.junitsuite }}-Unit Test Results-${{ github.event.repository.name }}

----------------------------------------------------------------------------------

**Comment by EnricoMi** [comment]
This has been fixed in version `v2`:

    uses: EnricoMi/publish-unit-test-result-action@v2
