### ISSUE TITLE
junit xsd doesn't require a failure body => GH checks api => properties/raw_details', nil is not a string.

### ISSUE THREAD

**Issue by meadisu27** [EnricoMi/publish-unit-test-result-action#48]
It would appear the body of the test failure is being supplied to GH's checks api via a required property. However, a failure body may not always be present.

```
2020-11-03 17:36:53 +0000 - publish-unit-test-results -  INFO - creating check
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 801, in <module>
    main(token, event, repo, commit, files, check_name, report_individual_runs, dedup_classes_by_file_name)
  File "/action/publish_unit_test_results.py", line 754, in main
    publish(token, event, repo, commit, stats, results['case_results'], check_name, report_individual_runs)
  File "/action/publish_unit_test_results.py", line 722, in publish
    publish_check(stats, cases)
  File "/action/publish_unit_test_results.py", line 613, in publish_check
    repo.create_check_run(name=check_name, head_sha=commit_sha, status='completed', conclusion='success', output=output)
  File "/action/githubext/Repository.py", line 78, in create_check_run
    headers={'Accept': 'application/vnd.github.antiope-preview+json'},
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Invalid request.\n\nFor 'properties/raw_details', nil is not a string.\nFor 'properties/raw_details', nil is not a string.", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}
```

**Comment by EnricoMi** [comment]
Thanks for raising this issue. Can you please provide me a test unit xml file that causes this issue?

**Comment by meadisu27** [comment]
```
<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="2" tests="2" time="0.0">    
    <testsuite disabled="0" errors="0" failures="1" name="Ensure S3 bucket has MFA delete enabled" package="checkov.terraform.checks.resource.aws.S3MFADelete" skipped="0" tests="1" time="0">
        <testcase classname="checkov.terraform.checks.resource.aws.S3MFADelete" file="/state/main.tf" name="terraform Ensure S3 bucket has MFA delete enabled aws_s3_bucket.state">
            <failure message="Resource &quot;aws_s3_bucket.state&quot; failed in check &quot;Ensure S3 bucket has MFA delete enabled&quot;" type="failure"/>
        </testcase>
    </testsuite>
    <testsuite disabled="0" errors="0" failures="1" name="Ensure the S3 bucket has access logging enabled" package="checkov.terraform.checks.resource.aws.S3AccessLogs" skipped="0" tests="1" time="0">
        <testcase classname="checkov.terraform.checks.resource.aws.S3AccessLogs" file="/state/main.tf" name="terraform Ensure the S3 bucket has access logging enabled aws_s3_bucket.state">
            <failure message="Resource &quot;aws_s3_bucket.state&quot; failed in check &quot;Ensure the S3 bucket has access logging enabled&quot;" type="failure"/>
        </testcase>
    </testsuite>
</testsuites>
```

**Comment by EnricoMi** [comment]
That is strange, this XML works for me. Is the repo public? Can you point me to the check run that has this issue?

**Comment by meadisu27** [comment]
Here is a public repo version of it, https://github.com/meadisu27/action-playground/

**Comment by EnricoMi** [comment]
Thanks for the public repo, I could reproduce and fix it in #49.

Please try the fix by using the action from branch `branch-nil-raw-details` instead of `master`:

    EnricoMi/publish-unit-test-result-action@branch-nil-raw-details

**Comment by meadisu27** [comment]
Tried it out. Looks good.

**Comment by EnricoMi** [comment]
Excellent, I will merge this into master and cut a new release. Thanks for raising this!

**Comment by EnricoMi** [comment]
Version v1.4 released.
