### ISSUE TITLE
Feature Request: Support Github Enterprise Server

### ISSUE THREAD

**Issue by Warashi** [EnricoMi/publish-unit-test-result-action#56]
Hi, thank you so much to provide this nice action.

I use Github Enterprise Server, so I want this action to support it.

**Comment by EnricoMi** [comment]
Hi, I am not sure what it requires to run on Enterprise Server, I presume all it needs is to use the correct API URL provided by `GITHUB_API_URL`: https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables

I can add this and you can try if this then works for you. Are there any errors when you run it as is?

**Comment by Warashi** [comment]
I want to try it.

When I run this action as is, I get this error.
```
2020-11-17 09:20:33 +0000 - publish-unit-test-results -  INFO - reading example.xml: ['example.xml']
Traceback (most recent call last):
  File "/action/publish_unit_test_results.py", line 855, in <module>
    report_individual_runs, dedup_classes_by_file_name)
  File "/action/publish_unit_test_results.py", line 801, in main
    comment_on_pr, report_individual_runs)
  File "/action/publish_unit_test_results.py", line 531, in publish
    repo = gh.get_repo(repo_name)
  File "/usr/local/lib/python3.6/site-packages/github/MainClass.py", line 334, in get_repo
    "GET", "%s%s" % (url_base, full_name_or_id)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by EnricoMi** [comment]
The action in master uses the URL provided via `GITHUB_API_URL` (automatically provided to the action by the workflow). Can you please run the action from master to test if this fixes it?

**Comment by Warashi** [comment]
worked successfully 🎉 
Thank you so much 😄

**Comment by EnricoMi** [comment]
That was easy. I presume your Enterprise Server has its own URL, not the public `https://api.github.com`?

**Comment by Warashi** [comment]
Yes, has own URL, not github.com.

**Comment by EnricoMi** [comment]
Excellent, thanks for raising this.
