### ISSUE TITLE
You must authenticate via a GitHub App

### ISSUE THREAD

**Issue by Mykullski** [EnricoMi/publish-unit-test-result-action#635]
Action Step
    - name: Publish Test Results Summary
      uses: EnricoMi/publish-unit-test-result-action@v2.18.0
      with:
        github_token: ${{ secrets.TOKEN }}
        action_fail: true
        files: |
          testresults/**/*.trx
          
Action Result
2024-10-23 22:44:50 +0000 - publish -  INFO - Available memory to read files: 29.0 GiB
2024-10-23 22:44:50 +0000 - publish -  INFO - Reading files testresults/**/*.trx (1 file, 3.1 KiB)
2024-10-23 22:44:50 +0000 - publish -  INFO - Detected 1 TRX file (3.1 KiB)
2024-10-23 22:44:50 +0000 - publish -  INFO - Finished reading 1 files in 0.01 seconds
2024-10-23 22:44:50 +0000 - publish -  INFO - Publishing success results for commit 4dd853374c06958f6aea292d17b415b3e1d0438c
Request POST /repos/ORG/REPO/check-runs failed with 403: Forbidden
2024-10-23 22:44:51 +0000 - github.GithubRetry -  INFO - Request POST /repos/ORG/REPO/check-runs failed with 403: Forbidden
Traceback (most recent call last):
  File "/action/publish_test_results.py", line 546, in <module>
    main(settings, gha)
  File "/action/publish_test_results.py", line 269, in main
    Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
  File "/action/publish/publisher.py", line 233, in publish
    data = self.publish_check(data)
  File "/action/publish/publisher.py", line 461, in publish_check
    check_run = self._repo.create_check_run(name=self._settings.check_name,
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 3[79](https://github.com/ORG/REPO/actions/runs/11489241672/job/31977631489#step:27:80)3, in create_check_run
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 537, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 702, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 799, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line [83](https://github.com/ORG/REPO/actions/runs/11489241672/job/31977631489#step:27:84)3, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 195, in getresponse
    r = verb(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line [93](https://github.com/ORG/REPO/actions/runs/11489241672/job/31977631489#step:27:94)4, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.8/site-packages/github/GithubRetry.py", line 183, in increment
    raise Requester.createException(response.status, response.headers, content)  # type: ignore
github.GithubException.GithubException: 403 {"message": "You must authenticate via a GitHub App.", "documentation_url": "https://docs.github.com/rest/checks/runs#create-a-check-run", "status": "403"}

**Comment by EnricoMi** [comment]
This action does not work with a PAT, it requires a Github App token.

Github Actions provide you a token via `secrets.GITHUB_TOKEN` (or simply don't provide a `github_token` option).

If you really have to povide a token other than `secrets.GITHUB_TOKEN`, you have to go through the process of creating a Github App.

**Comment by mrlacey** [comment]
I'm seeing this error reported when added to new projects.
I have the tokens working correctly on older projects and running the action on the projects with this previously added continues to work correctly. I believe this rules out an issue with the token.
Based on the link in the error message ( https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run )  it seems to be related to something with "check runs" failing and these being limited to 1000 runs. Could this be limiting the number of repos that can use this extension?
_Full disclosure, I do not understand what "check runs" are or what the linked documentation page is trying to say._

**Comment by mrlacey** [comment]
> I'm seeing this error reported when added to new projects. I have the tokens working correctly on older projects and running the action on the projects with this previously added continues to work correctly. I believe this rules out an issue with the token. Based on the link in the error message ( [docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#create-a-check-run) ) it seems to be related to something with "check runs" failing and these being limited to 1000 runs. Could this be limiting the number of repos that can use this extension? _Full disclosure, I do not understand what "check runs" are or what the linked documentation page is trying to say._

I take it back, I found the details on setting permissions and that has solved things.
I guess that there's some internal difference in settings of different projects based on when they were created.

**Comment by EnricoMi** [comment]
So I presume removing the `github_token: ${{ secrets.TOKEN }}` line fixes his for you?

**Comment by EnricoMi** [comment]
Btw., thanks for the support!

**Comment by mrlacey** [comment]
> So I presume removing the `github_token: ${{ secrets.TOKEN }}` line fixes his for you?

No, I added the required permissions for the build earlier in the script.: https://github.com/mrlacey/WpfColorHelper/commit/9ff675246f3ec908a72300c921a424986b02a5cf

**Comment by EnricoMi** [comment]
@Mykullski has your issue resolved?

**Comment by mark-bixler** [comment]
I have this same issue but passing in the input `github_token: ${{ secrets.GITHUB_TOKEN }}`

It seems to work on a step using a provided GitHub Runner, but this same process does not work using self-hosted runner in AWS.

```
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest", "status": "401"}
```

**Comment by EnricoMi** [comment]
@mark-bixler can you check the permissions of your `GITHUB_TOKEN` in the `Set up job` step like [this](https://github.com/EnricoMi/publish-unit-test-result-action/actions/runs/17793148807/job/50575058668#step:1:20)?
