### ISSUE TITLE
Testing dependabot branch fails with "Resource not accessible by integration"

### ISSUE THREAD

**Issue by Allcharles** [EnricoMi/publish-unit-test-result-action#95]
When running my workflow on dependabot branch `dependabot/npm_and_yarn/typescript-eslint/parser-4.18.0` I am receiving the following error:

```
2021-03-16T14:49:50.9184853Z Traceback (most recent call last):
2021-03-16T14:49:50.9185525Z   File "/action/publish_unit_test_results.py", line 89, in <module>
2021-03-16T14:49:50.9186069Z     main(settings)
2021-03-16T14:49:50.9186877Z   File "/action/publish_unit_test_results.py", line 32, in main
2021-03-16T14:49:50.9187889Z     Publisher(settings, gh).publish(stats, results.case_results)
2021-03-16T14:49:50.9188632Z   File "/action/publish/publisher.py", line 59, in publish
2021-03-16T14:49:50.9189519Z     check_run = self.publish_check(stats, cases)
2021-03-16T14:49:50.9190217Z   File "/action/publish/publisher.py", line 163, in publish_check
2021-03-16T14:49:50.9190781Z     output=output)
2021-03-16T14:49:50.9191375Z   File "/action/githubext/Repository.py", line 78, in create_check_run
2021-03-16T14:49:50.9192995Z     headers={'Accept': 'application/vnd.github.antiope-preview+json'},
2021-03-16T14:49:50.9194475Z   File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
2021-03-16T14:49:50.9195678Z     verb, url, parameters, headers, input, self.__customConnection(url)
2021-03-16T14:49:50.9196789Z   File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
2021-03-16T14:49:50.9197860Z     raise self.__createException(status, responseHeaders, output)
2021-03-16T14:49:50.9200050Z github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}
```

The full logs can be seen [here](https://github.com/QutEcoacoustics/workbench-client/actions/runs/657893351). The tests are XML formatted coburtura test results, I have attached the test files used for this workflow below: [Unit Test Results.zip](https://github.com/EnricoMi/publish-unit-test-result-action/files/6152835/Unit.Test.Results.OS.windows-latest.zip)

Any help would be appreciated.

**Comment by EnricoMi** [comment]
The "Resource not accessible by integration" usually occurs when the action runs on a `pull_request` event for a PR from a fork repository. In your situation, it seems to occur on a `push` event from a local branch created by dependabot. Looks like that event has the same restriction as a pull request from a fork.

What you will need is to follow the instructions for a fork repository: https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories

The root cause of this error is that for fork repositories (and apparently for local branches created by dependabot as well), `push` and `pull_request` events are not permissioned to create check runs or pull request comments on the target repository.

So what you should do:
1. disable "Publish Unit Test Results" for branches starting with `dependabot/`: `if: (! startsWith(GITHUB_REF, 'refs/heads/dependabot/'))`
2. create another workflow called `Dependabot` similar to the [Fork](https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories) workflow
3. enable it on `dependabot/` branches only, so replace `github.event.workflow_run.head_repository.full_name != github.repository` with `startsWith(GITHUB_REF, 'refs/heads/dependabot/')`

**Comment by EnricoMi** [comment]
The reason for the restriction might be this: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#insecure-external-code-execution

**Comment by EnricoMi** [comment]
I have reproduced this issue here: https://github.com/G-Research/spark-dgraph-connector/actions/runs/660330417

I have then removed the unit test result action from the workflow completely and added a dedicated workflow: unit-test-results.yml

https://github.com/G-Research/spark-dgraph-connector/blob/6951426f4fe3b063a83a36c89d44033680b9a5a3/.github/workflows/unit-test-results.yml

This workflow is generic and should work for you as well.

The dependabot branch then works: https://github.com/G-Research/spark-dgraph-connector/actions/runs/660795942

**Comment by Allcharles** [comment]
Thank you for the help and the quick reply. Do you have somewhere I can donate to you for your work on this repo?

**Comment by EnricoMi** [comment]
My pleasure! Thanks for bringing this to my attention. In fact, you made me setup dependabot to replicate this, and dependabot is pretty great, so I have now added it to all my projects, where it now works great along with this action. So win-win I would say.

Spread the word and use the action where ever you can :smile:.
